name: zero_hunger
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Google
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  google_maps_flutter: ^2.2.8

  # Location
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  uuid: ^3.0.7

  # Service
  http:

  # State
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4

  # Local Storage
  shared_preferences: ^2.0.18

  # Icon
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.16
  flutterfire_ui: ^0.4.3+20
  cloud_firestore: ^4.4.4

  # Image Picker
  image_picker: ^0.8.7+5
  transparent_image: ^2.0.1

  # Lottie
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # State
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/onboard/png/
    - assets/login/png/
    - assets/profile/png/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
